#if !canImport(ObjectiveC)
import XCTest

extension SwiftZ3Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftZ3Tests = [
        ("testBitwiseExpr", testBitwiseExpr),
        ("testFloatingPointExample2", testFloatingPointExample2),
        ("testFloatingPointExample2_withTypeSystem", testFloatingPointExample2_withTypeSystem),
        ("testFpaSolver", testFpaSolver),
        ("testFpaSolverWithOperators", testFpaSolverWithOperators),
        ("testSudokuExample", testSudokuExample),
        ("testTranslation", testTranslation),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SwiftZ3Tests.__allTests__SwiftZ3Tests),
    ]
}
#endif
